language: generic
os: linux
dist: bionic
services:
    - docker

before_install:
     - docker build -t ualban/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ualban/react-test npm test

after_success:
    - docker build -t ualban/multi-client ./client
    - docker build -t ualban/multi-ngnix ./ngnix
    - docker build -t ualban/multi-server ./server
    - docker build -t ualban/multi-worker ./worker
    # log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take them and push them to docker hub
    - docker push ualban/multi-client
    - docker push ualban/multi-ngnix
    - docker push ualban/multi-server
    - docker push ualban/multi-worker